export const EDUCATION_LOADING = "EDUCATION_LOADING";
export const GET_EDUCATION = "GET_EDUCATION";
export const GET_SKILL = "GET_SKILL";
export const ADD_SKILL = "ADD_SKILL";
export const SKILL_LOADING = "SKILL_LOADING";
